name: React Typescript Template CI Pipe
on:
  push:
    branches: [main, dev, ft/*]
  pull_request:
    branches: [main, dev]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install yarn dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile

      - name: Verify Typescript
        run: yarn tsc

      - name: Verify Eslint
        run: yarn eslint

      - name: Unit Testing
        run: yarn test --ci --coverage
